# Cloud Build configuration for deploying to Cloud Run
steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-f'
      - 'server/Dockerfile'
      - '-t'
      - 'gcr.io/$PROJECT_ID/mars-nexus-server:$BUILD_ID'
      - '-t'
      - 'gcr.io/$PROJECT_ID/mars-nexus-server:latest'
      - '.'

  # Push the image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/mars-nexus-server:$BUILD_ID'
  
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/mars-nexus-server:latest'

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'mars-nexus-server'
      - '--image'
      - 'gcr.io/$PROJECT_ID/mars-nexus-server:$BUILD_ID'
      - '--region'
      - 'us-east1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '2'
      - '--min-instances'
      - '1'
      - '--max-instances'
      - '10'
      - '--timeout'
      - '300'
      - '--set-env-vars'
      - 'NODE_ENV=production,FIREBASE_ADMIN_PROJECT_ID=mars-nexus,FIREBASE_ADMIN_CLIENT_EMAIL=firebase-adminsdk-fbsvc@mars-nexus.iam.gserviceaccount.com'
      - '--update-secrets'
      - 'FIREBASE_ADMIN_PRIVATE_KEY=firebase-admin-key:latest'

images:
  - 'gcr.io/$PROJECT_ID/mars-nexus-server:$BUILD_ID'
  - 'gcr.io/$PROJECT_ID/mars-nexus-server:latest'

options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

